### PR TITLE
New codebase for v. 0.5

### PR DESCRIPTION
**Pull request by sverzegnassi**

### CODE REVIEW

**Comment by sverzegnassi** [comment]
Keep it on hold, for the moment :)

**Comment by Flohack74** [comment]
I dont want to be nagging, but is it really a good idea to let a PR grow that big? In case smth went wrong it will be hard to roll back the stuff ;)

**Comment by sverzegnassi** [comment]
@Flohack74 It was hard to change a single feature without breaking the rest of the code, since a lot of functions and properties were references with no standard criteria. I've been trying a different (and better) way to reach the same result, however I found myself rewriting the same portions of code every ginle commit. By the way, code in this PR is almost a full rewriting of the QML front-end.

I don't expect to introduce new features in the proposed PR, but only consolidate the existing functionalities. The "dev version" available on the OpenStore is part of this strategy, so I wouldn't expect regressions at the end of the process[1]. Also, we are keeping testing each commit by our own, and tracking any small correction that might be required.

I would like to specify this wasn't an ordinary maintenance of the source code, and it wasn't either meant to be so. This looks more like the long-waited refactor of the source code that was necessary since the application moved from Ubuntu.Components 0.1 and 1.0 to the more recent 1.2 or 1.3. During the years, there has been a number of commits that increased the amount of obsolete and unoptimized code.

Yours is a good point anyway - and yes, it probably does not make any sense to push these changes in 'master'. Indeed, we might want to create a new branch for v. 0.5 instead.
What do you think?

[1] Well, if we consider the current state of v. 0.4, they would be anyway balanced by the huge improvements in terms of UI and functionalities :stuck_out_tongue_winking_eye:

**Comment by Flohack74** [comment]
Well I would approve it also here, working with many version and feature branches is good when you have the resources to manage it. For a small team I would always recommend to try to stick with 1 mainline branch, and PRs which are indeed kind of "external" branches. In my company we blocked committing to master, and people need to create branches for PRs instead.

So its up to you, but if you want to run 2 versions in OpenStore for a longer time, it might be worth to have 2 branches also to mirror that, and give people the chance to make PRs for both.

**Comment by nfsprodriver** [comment]
We really should merge that soon before it gets incompatible. The work from my and @sverzegnassi seems do be done for now. Try latest build from testing branch to see the changes...

**Comment by NeoTheThird** [comment]
I agree, it'd be good to have this in OTA-4. How was your experience @nfsprodriver? Would you be OK with that @sverzegnassi, or do you see something critical you want to get done before?

**Comment by sverzegnassi** [comment]
I gave it a look last week. Currently, armhf xenial version can not be built with clickable.

Long story short: 'libsmbclient' can't be installed in an 'armhf' container, because of issues with its python dependencies. It's still the same issue that affects filemanager-app since 2015[1].

For 15.04, I asked @bhdouglass to prepare a custom Docker container with preinstalled samba dev-libraries, we might still need the same for '16.04 armhf' and '16.04 amd64'.

@bhdouglass - could you please set up those Docker containers for us?

[1] https://lists.launchpad.net/ubuntu-touch-coreapps/msg00865.html

**Comment by mariogrip** [comment]
Due to reason [1] (+ other deps) filemanager is currently built as deb for xenial, this makes thins alot easier to build for both desktop and mobile. If it's ok to build as deb, i would suggest keeping it as deb.

**Comment by sverzegnassi** [comment]
@mariogrip I just saw your comment to issue #496 in ubports/ubuntu-touch repo. If that's okay for you, no reason to say no.

I'd only remind that a new version can only be released through an OTA, so a strong set of (manual) tests for the new codebase is required.

**Comment by bhdouglass** [comment]
@sverzegnassi I set up a `16.04-filemanager-armhf` docker container for you and pushed it to dockerhub. I can't do a 16.04 amd64 one because the ubuntu-sdk meta package is broken currently.

**Comment by mariogrip** [comment]
I have pushed this https://github.com/ubports/ubuntu-touch-meta/commit/ba71e3db6c5ebf4ffa5cd479606e5680c021e350 this installs the needed libs and install also install python things that had dependency issues, so no need for a special docker container anymore :fireworks: :confetti_ball:  @bhdouglass could i request a 16.04 container update pretty please? :D :D

**Comment by mariogrip** [comment]
@sverzegnassi So we decided to go the click way, exactly for the reason that we cannot update it independently from OTAs + it caused duplicates coming from vivid. So i have filter out the dependencies and installed them and fixed dependency issues with python.

**Comment by nfsprodriver** [comment]
We may not need that PR anymore because it's outdated. But I'll keep it open for discussion and create a PR from up to date testing branch...

**Pull request merged**
