### PR TITLE
bump version due to downgrade cases

### PR DESCRIPTION
**Pull request by nfsprodriver**
Fixes inconsistence of OpenStore and previously installed click packages using git revision.

### CODE REVIEW

**Comment by Flohack74** [comment]
Yes I suggest having less minors andminor-minors on versioning:
- 1 major for the overall version/series
- 1 minor for periodical releases
- 1 minor for hotfixes etc

So 0.6.0 is perfectly fine.

**Comment by Flohack74** [comment]
Or even bump it to 1.0

**Comment by NeoTheThird** [comment]
> Or even bump it to 1.0

If we do that, make it 1.0.0 please!

**Comment by mariogrip** [comment]
0.6.0 is best tbh

**Comment by nfsprodriver** [comment]
0.6.0 looks good

**Pull request merged**
